### PR TITLE
Import UIKit to fix build error.

### PR DESCRIPTION
**Pull request by stal888**
yes

### CODE REVIEW

**Comment by sweetmandm** [comment]
Just wondering - in what case was this a problem? Did you get the build error while making a Watch app or in some other circumstances?

**Comment by stal888** [comment]
Building a standard app with the iOS 9 SDK. FontInspector wouldn't compile because of the missing UIFont declaration.

**Comment by sweetmandm** [comment]
:+1: Thanks!

**Comment by stal888** [comment]
Thanks for the merge

**Pull request merged**
